package ru.pearx.teleporto;

import net.minecraft.util.EnumHand;
import net.minecraftforge.common.DimensionManager;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;
import ru.pearx.libmc.PXLMC;
import ru.pearx.teleporto.common.CommonProxy;
import ru.pearx.teleporto.common.caps.CapabilityRegistry;
import ru.pearx.teleporto.common.networking.NetworkManager;

import java.io.File;
import java.util.Collections;

/*
 * Created by mrAppleXZ on 14.07.17 13:29.
 */
@Mod(modid = Teleporto.MODID, version = Teleporto.VERSION, acceptedMinecraftVersions = Teleporto.MCVERSION, name = Teleporto.NAME)
public class Teleporto
{
    public static final String NAME = "Teleporto";
    public static final String MODID = "teleporto";
    public static final String VERSION = "@VERSION@";
    public static final String MCVERSION = "@MCVERSION@";

    @Mod.Instance(Teleporto.MODID)
    public static Teleporto INSTANCE;

    @SidedProxy(clientSide = "ru.pearx.teleporto.client.ClientProxy", serverSide = "ru.pearx.teleporto.client.ServerProxy")
    public static CommonProxy proxy;

    public static File config;
    public static int spawnDimension;

    @Mod.EventHandler
    public static void preInit(FMLPreInitializationEvent e)
    {
        ModMetadata data = e.getModMetadata();
        data.url = "TODO"; //TODO
        data.authorList = Collections.singletonList("mrAppleXZ");
        data.autogenerated = false;
        data.description = "A simple teleportation mod for Minecraft.";
        data.version = VERSION;
        data.modId = MODID;
        data.name = NAME;

        config = e.getSuggestedConfigurationFile();
        Configuration conf = new Configuration(config);
        spawnDimension = conf.getInt("Spawn Dimension", "GENERAL", 0, Integer.MIN_VALUE, Integer.MAX_VALUE, "ID of the dimension that will be used for the Primal Talisman.");
        if(conf.hasChanged())
            conf.save();
    }

    @Mod.EventHandler
    public static void init(FMLInitializationEvent e)
    {
        NetworkManager.setup();
        CapabilityRegistry.setup();
    }
}
